server:
  port: 45009
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jspro_demo?useOldAliasMetadataBehavior=true&createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    initialSize: 1
    maxActive: 20
    maxWait: 600000
  application:
    name: "jspro_demo"
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
  flyway:
    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db
    encoding: utf-8
  aop:
    auto: true #启动aop配置
mybatis-plus:
  mapper-locations: classpath:com/summit/dao/**/*.xml
  config-location: classpath:mybatis-config.xml
mq:
  name-service: 127.0.0.1:9876
  producerGroup: jsproProducer
  consumerGroup: jsproConsumer
  enable: false
  topic: jsproTest
  tag: testTag
#导入、导出路径
fileUploadPath:
  path: d:/upload
file:
  rootPath: 'D:'
  sonPath: '/img/'
app:
  auth-white-list:
    # business url
    - '/**/*.jpg'
    - '/**/*.jpeg'
    - '/**/*.png'
    - '/**/not-auth/**'
    # actuator url
    - '/actuator/**'
    # swagger ui
    - '/v2/api-docs'
    - '/**/v2/api-docs'
    - '/swagger-resources/**'
    - '/swagger-ui.html'
    - '/swagger/api-docs'
    - '/webjars/**'
    - '/**/wechat/**'

